version: "3"
services:
  frontend:
    build: ./frontend
    image: ${DOCKER_USERNAME}/devconnector-frontend

  backend:
    build: ./backend
    image: ${DOCKER_USERNAME}/devconnector-backend

  proxy:
    build: ./proxy
    image: ${DOCKER_USERNAME}/devconnector-proxy
    ports:
      - "5000:5000"
