apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    pod: backend
  ports:
    - port: 5000
      # targets TCP port 8080 on any Pod with the app: api-feed label; targetPort is the port the container accepts traffic on; port is the abstracted Service port

