apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: backend
  template:
    metadata:
      labels:
        pod: backend
    spec:
      containers:
        - name: backend
          image: hungapp/devconnector-backend
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

          env:
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REGION
            - name: STAGE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: STAGE
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: GITHUB_CLIENT_SECRET
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
