apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: frontend
  template:
    metadata:
      labels:
        pod: frontend
        api: external
    spec:
      containers:
        - image: hungapp/devconnector-frontend
          name: frontend
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

      restartPolicy: Always
